version: '3'

services:
    postgres:
        build:
            context: .
            dockerfile: ./postgres/dockerfile
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=simplebank
        ports:
            - "5432:5432"
        container_name: postgres

    postgres-gui:
        image: donnex/pgweb
        command: -s --bind=0.0.0.0 --listen=8080 --url postgresql://postgres:secret@postgres/simplebank?sslmode=disable
        links:
            - postgres:postgres
        ports: 
            - "9232:8080"
        depends_on: 
            - postgres